apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-calci-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-calci-app
  template:
    metadata:
      labels:
        app: java-calci-app
    spec:
      containers:
      - name: nanivardhan/calciapp
        image: nanivardhan/calciapp:v1.0
        command: ["java", "Calculator"]
